import yaml

from snakemake.utils import min_version, validate

min_version("9.19")


# Load the minimal example configuration.
configfile: workflow.source_path("../config/config.yaml")


# Validate the configuration using the schema file.
validate(config, workflow.source_path("internal/config.schema.yaml"))

# Load internal (non user configurable) settings separately to keep them protected.
with open(workflow.source_path("internal/settings.yaml"), "r") as f:
    internal = yaml.safe_load(f)


# Add all your Snakemake includes here.
include: "rules/module_geo_boundaries.smk"
include: "rules/module_powerplants.smk"
include: "rules/module_area_potentials.smk"


POWERPLANTS = ["bioenergy", "fossil", "geothermal", "hydropower", "nuclear", "large_solar", "wind"]

rule all:
    default_target: True
    input:
        expand(
            "resources/powerplants/results/BALTIC/powerplants/unadjusted/{powerplants}.parquet",
            powerplants=POWERPLANTS
        ),
    message:
        "Generate all files."
