import yaml

from snakemake.utils import min_version, validate

min_version("9.19")


# Load the minimal example configuration.
configfile: workflow.source_path("../config/config.yaml")


# Validate the configuration using the schema file.
validate(config, workflow.source_path("internal/config.schema.yaml"))

# Load internal (non user configurable) settings separately to keep them protected.
with open(workflow.source_path("internal/settings.yaml"), "r") as f:
    internal = yaml.safe_load(f)


# Add all your Snakemake includes here.
include: "rules/module_geo_boundaries.smk"


# include: "rules/module_powerplants.smk"


rule all:
    default_target: True
    output:
        "INVALID",
    log:
        stderr="<logs>/all.stderr",
    conda:
        "envs/module.yaml"
    message:
        "ERROR: Invalid `rule all:` call"
    shell:
        'echo "This workflow must be called as a snakemake module." > {log.stderr}'
