import yaml

from snakemake.utils import min_version, validate

min_version("9.19")


# Load the example configuration. This will be overridden by users.
configfile: workflow.source_path("../config/config.yaml")


# Validate the configuration using the schema file.
validate(config, workflow.source_path("internal/config.schema.yaml"))

# Load internal settings separately so users cannot modify them.
with open(workflow.source_path("internal/settings.yaml"), "r") as f:
    internal = yaml.safe_load(f)


# Add all your includes here.
include: "rules/module_geo_boundaries.smk"
include: "rules/module_powerplants.smk"


# Add additional files to be delivered alongside the workflow here.
# This is needed e.g. for python code files that are never
# explicitly used as a script or input in a snakemake rule.
# e.g.: workflow.source_path("scripts/_utils.py")

rule all:
    message:
        "Main snakemake rule."
    default_target: True
    input:
        "resources/modules/geo_boundaries/example/results/shapes.parquet",
        "resources/modules/geo_boundaries/MEX/results/shapes.parquet",
        "resources/modules/powerplants/results/MEX/aggregated/adjusted/fossil.parquet",
        "resources/modules/powerplants/results/MEX/aggregated/adjusted/hydropower.parquet"
    log:
        stderr="<logs>/all.stderr",
