# You can configure muliple 'shape' scenarios
# All you need is:
# - country_id in alpha3 (e.g., PRT -> Portugal)
# - source: dataset to use (overture, nuts, geoboundaries, gadm)
# - subtype: resolution (varies per dataset)
#
# Some sources might need extra parameters!
# Check the link below for examples
# https://github.com/modelblocks-org/module_geo_boundaries/blob/main/config/config.yaml
crs:
  projected: "epsg:3857"
  geographic: "epsg:4326"
scenarios:
  PORTUGAL:  # Portugal, with Azores and Madeira
    crs:
      projected: EPSG:3035  # ETRS89-extended / LAEA Europe
    countries:
      "PRT":
        subtype: "3" # Small regions
        source: "nuts"
        resolution: 01M
        year: 2024
        extra_eez: [8361, 8363]  # Exclusive economic zones for Azores and Madeira

  BALTIC:  # Baltic countries with disaggregated marine areas
    voronoi_eez:
      enabled: True  # Split maritime exclusive economic zones to match subregions
    crs:
      projected: EPSG:3035  # ETRS89-extended / LAEA Europe
    countries:
      "EST":
        subtype: 0  # National
        source: "geoboundaries"
        release_type: "gbOpen"
      "LTU":
        subtype: 1 # Subnational
        source: "geoboundaries"
        release_type: "gbOpen"
      "LVA":
        subtype: 1 # Subnational
        source: "geoboundaries"
        release_type: "gbOpen"
