$schema: "https://json-schema.org/draft/2020-12/schema"
description: "Schema for user-provided configuration files."
type: object
additionalProperties: false
properties:
  scenario:
    description: |
      Shape scenario to feed into modules that do not support that wildcard.
    type: string
